# Site settings
title: Manivannan
name: Manivannan
#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Blog
   url: http://http://mani-cibi.blogspot.in/
 - title: GitHub
   url: https://github.com/cibi246
#Any buzzword skills you want to include
skills:
 - Java
 - Spring MVC
 - Spring Boot
 - Spring Data JPA
#Work experience is required
roles:
 - title: Application Developer
   start: 2014
   end: Ongoing
   employer: Accenture Solutions Private Limited
   description: <br/> I am a Application developer, working across the full-stack, I am involved in all aspects of the technology including the website and back-end services.
#Education is required
education:
 - level: Bachelor of Engineering (B.E.)
   date: 2013
   subject: Computer Science and Engineering
   school: SNS College of Technology - Affiliated to Anna University, Chennai
#This section is optional (as is the image link below)
